[package]
name = "caprust-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ureq = { workspace = true }
sha2 = "0.10"
blake3 = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sys-locale = { workspace = true }
